# [Frozen Lake](https://gym.openai.com/envs/FrozenLake-v0)

- Dynamic Programming Algorithms

    - Policy iteration (includes policy evaluation and policy improvement)
    - Value iteration

- Temporal Different Algorithms
    - Sarsa
    - Q-learning
    
- Optional algorithms (need not submit)
    - Double q-learning
    - Expected Sarsa
   

The sub-routines for the algorithms are in `algorithms.py`.

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import gym
import time
from IPython.display import clear_output
from lake_envs import *
from algorithms import *
np.set_printoptions(precision=3)
# Make the two versions of the environment
env_d = gym.make("Deterministic-4x4-FrozenLake-v0")
env_s = gym.make("Stochastic-4x4-FrozenLake-v0")
RENDER_ENV = True

C:\Users\hocke\anaconda3\envs\hw6\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


# Dynamic Programming
## Policy Iteration on Deterministic Frozen Lake

In [3]:
print("\n" + "-"*25 + "\nBeginning Policy Iteration\n" + "-"*25)

V_pi, p_pi = policy_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
render_single(env_d, p_pi, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Policy Iteration
-------------------------

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


## Value Iteration on Deterministic Frozen Lake

In [4]:
print("\n" + "-"*25 + "\nBeginning Value Iteration\n" + "-"*25)

V_vi, p_vi = value_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
render_single(env_d, p_vi, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Value Iteration
-------------------------

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


## Policy Iteration  on Stochastic Frozen Lake

In [5]:
print("\n" + "-"*25 + "\nBeginning Policy Iteration\n" + "-"*25)
V_pi, p_pi = policy_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
render_single(env_s, p_pi, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Policy Iteration
-------------------------

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG


## Value Iteration on Stochastic Frozen Lake

In [6]:
print("\n" + "-"*25 + "\nBeginning Value Iteration\n" + "-"*25)

V_vi, p_vi = value_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
render_single(env_s, p_vi, 100, show_rendering=RENDER_ENV) 


-------------------------
Beginning Value Iteration
-------------------------

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FF

KeyboardInterrupt: 

## Evaluate Dynamic Programming Algorithms


Evaluate policy iteration on stochastic FrozenLake.  Running the same policy over multiple episodes will result in different outcomes (final reward) due to stochastic transitions in the environment.

In [ ]:
print("Policy Iteration on Stochastic FrozenLake:")
V_pi, p_pi = policy_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
evaluate(env_s, p_pi, max_steps=100, max_episodes=1000)

Policy Iteration on Stochastic FrozenLake:
> Average reward over 1000 episodes:			 0.722
> Percentage of episodes a terminal state reached:			 94%


0.722

Evaluate value iteration on stochastic FrozenLake. 

In [ ]:
print("\nValue Iteration on Stochastic FrozenLake:")
V_vi, p_vi = value_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
evaluate(env_s, p_vi, max_steps=100, max_episodes=1000)


Value Iteration on Stochastic FrozenLake:
> Average reward over 1000 episodes:			 0.699
> Percentage of episodes a terminal state reached:			 93%


0.699

# Temporal Difference
## Sarsa on Deterministic Frozen Lake

In [ ]:
print("\n" + "-"*25 + "\nBeginning Sarsa on the deterministic environment\n" + "-"*25)

Q_ql, p_ql = sarsa(env_d, env_d.nS, env_d.nA, gamma=0.9, epsilon=0.6,
                   alpha=0.05, max_steps=100, max_episodes=100000)
display(p_ql)
render_single(env_d, p_ql, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Sarsa on the deterministic environment
-------------------------


array([1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0])


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


## Sarsa on Stochastic Frozen Lake

In [ ]:
print("\n" + "-"*25 + "\nBeginning Sarsa on the stochastic environment\n" + "-"*25)

Q_ql, p_ql  = sarsa(env_s, env_s.nS, env_s.nA, gamma=0.9, epsilon = 0.6,
                               alpha = 0.05, max_steps = 100, max_episodes=100000)
display(p_ql)
render_single(env_s, p_ql, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Q-learning on the stochastic environment
-------------------------


array([1, 1, 0, 3, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0])


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Episode reward: 0.000000


## Q-Learning on Deterministic Frozen Lake

In [ ]:
print("\n" + "-"*25 + "\nBeginning Q-learning on the deterministic environment\n" + "-"*25)

Q_ql, p_ql  = q_learning(env_d, env_d.nS, env_d.nA, gamma=0.9, epsilon = 0.6,
                         alpha=0.05, max_steps=100, max_episodes=200000)
display(p_ql)
render_single(env_d, p_ql, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Q-learning on the deterministic environment
-------------------------


array([1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0])


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


## Q-Learning on Stochastic Frozen Lake

In [ ]:
print("\n" + "-"*25 + "\nBeginning Q-learning on the stochastic environment\n" + "-"*25)

Q_ql, p_ql  = q_learning(env_s, env_s.nS, env_s.nA, gamma=0.9, epsilon = 0.6,
                         alpha=0.05, max_steps=100, max_episodes=200000)
display(p_ql)
render_single(env_s, p_ql, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Q-learning on the stochastic environment
-------------------------


array([0, 3, 2, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 2, 0])


SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


## Evaluate Temporal Difference Algorithms

In [ ]:
print("\nSarsa on Stochastic FrozenLake:")
Q_ql, p_ql  = sarsa(env_s, env_s.nS, env_s.nA, gamma=0.9, epsilon = 0.6,
                               alpha = 0.05, max_steps = 100, max_episodes=100000)
evaluate(env_s, p_ql, max_steps=200, max_episodes=10000)


Sarsa on Stochastic FrozenLake:
> Average reward over 10000 episodes:			 0.1183
> Percentage of episodes a terminal state reached:			 100%


0.1183

In [ ]:
print("\nQ-Learning on Stochastic FrozenLake:")
Q_ql, p_ql  = q_learning(env_s, env_s.nS, env_s.nA, gamma=0.9, epsilon = 0.6,
                         alpha=0.05, max_steps=100, max_episodes=200000)
evaluate(env_s, p_ql, max_steps=200, max_episodes=10000)


Q-Learning on Stochastic FrozenLake:
> Average reward over 10000 episodes:			 0.418
> Percentage of episodes a terminal state reached:			 100%


0.418

## Double Q-Learning on Deterministic Frozen Lake

In [ ]:
print("\n" + "-"*25 + "\nBeginning Double Q-learning on the deterministic environment\n" + "-"*25)

Q_ql, Q_q2, p_ql = double_q_learning(env_d, env_d.nS, env_d.nA, gamma=0.9, epsilon=0.6,
                                     alpha=0.05, max_steps=100, max_episodes=200000)
display(p_ql)
render_single(env_d, p_ql, 100, show_rendering=RENDER_ENV)


-------------------------
Beginning Double Q-learning on the deterministic environment
-------------------------


array([1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0])


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Episode reward: 1.000000


In [ ]:
print("\nDouble Q-Learning on Stochastic FrozenLake:")
Q_ql, Q_q2, p_ql = double_q_learning(env_s, env_s.nS, env_s.nA, gamma=0.9, epsilon=0.6,
                                     alpha=0.05, max_steps=100, max_episodes=200000)
evaluate(env_s, p_ql, max_steps=200, max_episodes=10000)


Double Q-Learning on Stochastic FrozenLake:
> Average reward over 10000 episodes:			 0.6281
> Percentage of episodes a terminal state reached:			 100%


0.6281

## Optimizing the parameters

In [ ]:
def optimize_parameters(algorithm):
    gamma = [0.8, 0.9]
    epsilon = [0.6, 0.7, 0.8]
    alpha = [0.05, 0.1, 0.15]
    max_episodes = [100000, 200000]
    max_score = 0
    optimal_parameters = {}
    for g in gamma:
        for e in epsilon:
            for a in alpha:
                for m in max_episodes:
                    score_sum = 0
                    runs = 3
                    for _ in range(runs):
                        Q_pl, p_ql = algorithm(env_s, env_s.nS, env_s.nA, gamma=g, epsilon=e,
                                            alpha=a, max_steps=100, max_episodes=m)
                        score_sum += evaluate(env_s, p_ql, max_steps=200, max_episodes=10000)
                    avg_score = score_sum / runs
                    if avg_score > max_score:
                        max_score = avg_score
                        optimal_parameters['gamma'] = g
                        optimal_parameters['epsilon'] = e
                        optimal_parameters['alpha'] = a
                        optimal_parameters['max_episodes'] = m
    return optimal_parameters

In [ ]:
optimal_sarsa_parameters = optimize_parameters(sarsa)
# 1 hour run time. {'gamma': 0.9, 'epsilon': 0.6, 'alpha': 0.05, 'max_episodes': 100000}
optimal_sarsa_parameters


> Average reward over 10000 episodes:			 0.2142
> Percentage of episodes a terminal state reached:			 100%


KeyboardInterrupt: 

In [ ]:
optimal_q_learning_parameters = optimize_parameters(q_learning)
# 1 hour run time {'gamma': 0.9, 'epsilon': 0.6, 'alpha': 0.05, 'max_episodes': 200000}
optimal_q_learning_parameters


> Average reward over 10000 episodes:			 0.4538
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.2854
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.079
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.2412
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.3383
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.1365
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.2444
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.2918
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:			 0.2385
> Percentage of episodes a terminal state reached:			 100%
> Average reward over 10000 episodes:	

{'gamma': 0.9, 'epsilon': 0.6, 'alpha': 0.05, 'max_episodes': 200000}